### ISSUE TITLE
inferno-collapse-perf slower than stackcollapse-perf.pl

### ISSUE THREAD

**Issue by gatoWololo** [jonhoo/inferno#178]
Hello, I tried using inferno since the perl version of flamegraph is too slow. Not sure if this is a known pathological case but the attached perf record runs in about the same or slower than the perl version.

Sample times and execution:
```shell
gatowololo> time perf script -i crdt_w1.perf_record | stackcollapse-perf.pl > crdt_w1.folded
________________________________________________________
Executed in  395.95 secs   fish           external 
   usr time  246.34 secs   34.69 millis  246.31 secs 
   sys time  151.03 secs    4.47 millis  151.02 secs 

gatowololo> time perf script -i crdt_w1.perf_record | inferno-collapse-perf > crdt_w1.folded.inferno
________________________________________________________
Executed in  434.87 secs   fish           external 
   usr time  267.35 secs    4.19 millis  267.35 secs 
   sys time  168.60 secs    0.00 millis  168.60 secs 

gatowololo> time perf script -i crdt_w1.perf_record | ~/inferno/target/release/inferno-collapse-perf > crdt_w1.folded.inferno
________________________________________________________
Executed in  346.44 secs   fish           external 
   usr time  217.16 secs    0.42 millis  217.16 secs 
   sys time  130.37 secs    4.28 millis  130.37 secs 
```

Perf record: [crdt.tar.gz](https://github.com/jonhoo/inferno/files/4738433/crdt.tar.gz)

I tried both via `cargo install inferno` and compiling from source with `--release`. Is this expected behavior or am I executing something wrong?

Thank you.

**Comment by jonhoo** [comment]
Huh, that's interesting. The last run looks like it's faster, but the first slower... Could you try running these through [hyperfine](https://github.com/sharkdp/hyperfine) to see if this is just noise or actually a runtime difference? Generally, collapsing is bottlenecked by the performance of `perf script`, not the actual collapser, so that may also be it. Could you try:
```console
$ perf script -i crdt_w1.perf_record > crdt_w1.script
```
And then try running the collapsers on that input directly. That should eliminate any noise from `perf script`.

**Comment by jonhoo** [comment]
cc @jasonrhansen

**Comment by gatoWololo** [comment]
I see. Yes. Once I write the `perf script` output to a file and then run `inferno-collapse-perf` I get the expected performance. Thanks!
