### ISSUE TITLE
feature request - implement skip_after

### ISSUE THREAD

**Issue by romange** [jonhoo/inferno#221]
Or k bottom frames if you consider flamegraph order.

The attached image demonstrates the problem. The process threads have different names, but besides this they are completely homogenous. I would like to have an option of skipping k root frames in order to merge relevant stacks together and reduce unneeded noise. 

![image](https://user-images.githubusercontent.com/3674760/137524455-e246991c-1a41-4abf-a886-9cbe07416a70.png)

**Comment by jonhoo** [comment]
I've run into this in the past too, but I don't think top/bottom k frames is actually good enough because every now and again you'll end up with two stacks that are "the same" (as yours are above), but where the differentiating bottoms are of different heights. For example, in `tokio`, depending on whether a future runs on a worker as part of regular execution, or after having been stolen from another worker, the distance from the bottom will differ by 1: the "steal" function. If you wanted to look at where the cycles in your futures are going, what you'd _really_ want is "strip everything up to a frame by this name" rather "strip the k first frames". Basically something like a `skip_until`. And I think that'd work for your case too?

Any chance you have time to write up a PR?
