### ISSUE TITLE
No version 5 of dashmap

### ISSUE THREAD

**Issue by dmilith** [jonhoo/inferno#229]
Please update Cargo.toml, since it contains dashmap in version 5, updating it to version 4 resolves the problem

**Comment by jonhoo** [comment]
That's really weird! There _was_ a [dashmap 5.0.0](https://crates.io/crates/dashmap/5.0.0), but it seems it [was yanked](https://github.com/xacrimon/dashmap/issues/177) due to [an unsoundness bug](https://rustsec.org/advisories/RUSTSEC-2022-0002.html). A new release should be out in a couple of days according to the maintainer.

**Comment by jonhoo** [comment]
Fixed in 0.10.11 :tada:
