### ISSUE TITLE
Add back demangling support

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/inferno#87]
Prior to #74, we had support for demangling function names (although only with `--inline`). While perf is _supposed_ to be doing it already (see [`--demangle`](http://man7.org/linux/man-pages/man1/perf-script.1.html)) there are [reports](https://www.reddit.com/r/rust/comments/b08oex/cargoflamegraph_generate_flame_graphs_directly/eidhhz8/) that it doesn't demangle everything super well. Having our own demangling step using one of the [many demangling crates](https://crates.io/search?q=demangle&sort=recent-downloads) seems like it might be a good idea!

**Comment by jasonrhansen** [comment]
I added support for this in a branch using the `symbolic_demangle` crate. The problem is perf is already doing a great job demangling function names for me in all of the tests I've tried.

I used perf on some Rust programs to see if I could ever get function names that don't demangle correctly. The only way the names come out mangled is if I explicitly pass `--no-demangle` to perf script. I wonder why other people are getting different results.

Have you seen mangled Rust names from perf?

**Comment by jasonrhansen** [comment]
BTW, if I do pass `--no-demangle` to perf script, my branch's version of `inferno-collapse-perf` successfully demangles the function names. I could create some tests this way, but I'm wondering why perf's demangling isn't working for some people.

**Comment by jonhoo** [comment]
It could be that those people are using older versions of `perf` with broken or outdated demangling. Given your experiments, I'm inclined to just close this and leave `perf` to deal with it. If anyone having this problem could provide some more context, that'd be great!

**Comment by king6cong** [comment]
on macOS, 
```sudo flamegraph rg``` will produce mangled names:
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/302560/60395092-d4bf8e00-9b60-11e9-9943-20d71bf590c7.png">

**Comment by jasonrhansen** [comment]
@king6cong This makes sense. The testing I did before was only for `perf` since `inferno` didn't yet support `DTrace`. Since you're on macOS, it's using `DTrace`. `DTrace` tries to demangle the names, but I believe it's demangling `Rust` names like `C++`. This sort of works, but not very well. After `DTrace` does its demangling, the result can't be demangled with the `rustc` demangler.

One way we could work around this is to pass the `-xmangled` option to `dtrace` so the names remain mangled. Then we could change the `dtrace` collapser to demangle the names. This would give much better results.
